<?php

use Illuminate\Database\Seeder;
use App\Blog;

class BlogsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
        	['title' => 'Cách dùng cảm biến chuyển động PIR sensor', 'description' => 'Xã hội ngày càng phát triển, người giàu ngày càng giàu. vì vậy xã hội cũng xảy ra một số tệ nạn trộm cướp tài sản. Hôm nay minh giới thiệu với các bạn một mạch báo trộm mini và bạn cũng có thể mở rộng lên theo ý tưởng riêng của bạn.', 'slug' => 'cach-dung-cam-bien-chuyen-dong-pir-senso', 'image' => 'https://nshopvn.com/wp-content/uploads/2019/03/cach-dung-cam-bien-chuyen-dong-300x225.jpg', 'content' => 'Nếu như đã làm việc với các module này thì không ít trong các bạn có thể đã gặp nhiều vấn đề khó giải quyết liên quan tới xung đột thư viện (như tôi ). Ngoài ra các module này có khoảng cách thu phát sóng khá ngắn (khoảng 30m nếu đã hàn thêm anten), lại không thể thu phát hai chiều. Vì những lý do trên, tôi đã tìm kiếm một loại module không dây khác để thay thế cho các module 433Mhz nhằm khắc phục các điểm yếu trên. Tìm kiếm trên mạng tôi đã tìm được loại module NRF24L01 sử dụng sóng 2.4Ghz tạm thời giải quyết được khá ổn những điểm yếu của module 433Mhz.'],
        	['title' => 'Cách dùng cảm biến chuyển động PIR sensor', 'description' => 'Xã hội ngày càng phát triển, người giàu ngày càng giàu. vì vậy xã hội cũng xảy ra một số tệ nạn trộm cướp tài sản. Hôm nay minh giới thiệu với các bạn một mạch báo trộm mini và bạn cũng có thể mở rộng lên theo ý tưởng riêng của bạn.', 'slug' => 'cach-dung-cam-bien-chuyen-dong-pir-nsor', 'image' => 'https://nshopvn.com/wp-content/uploads/2019/03/cach-dung-cam-bien-chuyen-dong-300x225.jpg', 'content' => 'Nếu như đã làm việc với các module này thì không ít trong các bạn có thể đã gặp nhiều vấn đề khó giải quyết liên quan tới xung đột thư viện (như tôi ). Ngoài ra các module này có khoảng cách thu phát sóng khá ngắn (khoảng 30m nếu đã hàn thêm anten), lại không thể thu phát hai chiều. Vì những lý do trên, tôi đã tìm kiếm một loại module không dây khác để thay thế cho các module 433Mhz nhằm khắc phục các điểm yếu trên. Tìm kiếm trên mạng tôi đã tìm được loại module NRF24L01 sử dụng sóng 2.4Ghz tạm thời giải quyết được khá ổn những điểm yếu của module 433Mhz.'],
        	['title' => 'Cách dùng cảm biến chuyển động PIR sensor', 'description' => 'Xã hội ngày càng phát triển, người giàu ngày càng giàu. vì vậy xã hội cũng xảy ra một số tệ nạn trộm cướp tài sản. Hôm nay minh giới thiệu với các bạn một mạch báo trộm mini và bạn cũng có thể mở rộng lên theo ý tưởng riêng của bạn.', 'slug' => 'cach-dung-cam-bien-chuyen-dong-sensor', 'image' => 'https://nshopvn.com/wp-content/uploads/2019/03/cach-dung-cam-bien-chuyen-dong-300x225.jpg', 'content' => 'Nếu như đã làm việc với các module này thì không ít trong các bạn có thể đã gặp nhiều vấn đề khó giải quyết liên quan tới xung đột thư viện (như tôi ). Ngoài ra các module này có khoảng cách thu phát sóng khá ngắn (khoảng 30m nếu đã hàn thêm anten), lại không thể thu phát hai chiều. Vì những lý do trên, tôi đã tìm kiếm một loại module không dây khác để thay thế cho các module 433Mhz nhằm khắc phục các điểm yếu trên. Tìm kiếm trên mạng tôi đã tìm được loại module NRF24L01 sử dụng sóng 2.4Ghz tạm thời giải quyết được khá ổn những điểm yếu của module 433Mhz.'],
        	['title' => 'Cách dùng cảm biến chuyển động PIR sensor', 'description' => 'Xã hội ngày càng phát triển, người giàu ngày càng giàu. vì vậy xã hội cũng xảy ra một số tệ nạn trộm cướp tài sản. Hôm nay minh giới thiệu với các bạn một mạch báo trộm mini và bạn cũng có thể mở rộng lên theo ý tưởng riêng của bạn.', 'slug' => 'cach-dung-cam-dong-pir-sensor', 'image' => 'https://nshopvn.com/wp-content/uploads/2019/03/cach-dung-cam-bien-chuyen-dong-300x225.jpg', 'content' => 'Nếu như đã làm việc với các module này thì không ít trong các bạn có thể đã gặp nhiều vấn đề khó giải quyết liên quan tới xung đột thư viện (như tôi ). Ngoài ra các module này có khoảng cách thu phát sóng khá ngắn (khoảng 30m nếu đã hàn thêm anten), lại không thể thu phát hai chiều. Vì những lý do trên, tôi đã tìm kiếm một loại module không dây khác để thay thế cho các module 433Mhz nhằm khắc phục các điểm yếu trên. Tìm kiếm trên mạng tôi đã tìm được loại module NRF24L01 sử dụng sóng 2.4Ghz tạm thời giải quyết được khá ổn những điểm yếu của module 433Mhz.'],
        	['title' => 'Cách dùng cảm biến chuyển động PIR sensor', 'description' => 'Xã hội ngày càng phát triển, người giàu ngày càng giàu. vì vậy xã hội cũng xảy ra một số tệ nạn trộm cướp tài sản. Hôm nay minh giới thiệu với các bạn một mạch báo trộm mini và bạn cũng có thể mở rộng lên theo ý tưởng riêng của bạn.', 'slug' => 'cach-cam-bien-chuyen-dong-pir-sensor', 'image' => 'https://nshopvn.com/wp-content/uploads/2019/03/cach-dung-cam-bien-chuyen-dong-300x225.jpg', 'content' => 'Nếu như đã làm việc với các module này thì không ít trong các bạn có thể đã gặp nhiều vấn đề khó giải quyết liên quan tới xung đột thư viện (như tôi ). Ngoài ra các module này có khoảng cách thu phát sóng khá ngắn (khoảng 30m nếu đã hàn thêm anten), lại không thể thu phát hai chiều. Vì những lý do trên, tôi đã tìm kiếm một loại module không dây khác để thay thế cho các module 433Mhz nhằm khắc phục các điểm yếu trên. Tìm kiếm trên mạng tôi đã tìm được loại module NRF24L01 sử dụng sóng 2.4Ghz tạm thời giải quyết được khá ổn những điểm yếu của module 433Mhz.'],
        ];

        Blog::insert($data);
    }
}
